# Generated by Django 3.1.3 on 2020-11-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='ads_description',
            new_name='advertisement_description',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ads_pictures',
            new_name='advertisement_pictures',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ads_slug',
            new_name='advertisement_slug',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='ads_title',
            new_name='advertisement_title',
        ),
    ]
